services:

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    expose:
      - "6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    expose:
      - "5672"
      - "15672"

  product-service:
    build:
      context: .
      dockerfile: ./apps/product-service/Dockerfile
    image: 247661383205.dkr.ecr.eu-north-1.amazonaws.com/product-service:latest
    container_name: product-service
    restart: unless-stopped
    env_file:
      - ./apps/product-service/.env
    environment:
      REDIS_URL: redis://redis:6379
    expose:
      - "8003"
    depends_on:
      - redis

  user-service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
    image: 247661383205.dkr.ecr.eu-north-1.amazonaws.com/user-service:latest
    container_name: user-service
    restart: unless-stopped
    env_file:
      - ./apps/user-service/.env
    expose:
      - "8004"

  order-service:
    build:
      context: .
      dockerfile: ./apps/order-service/Dockerfile
    image: 247661383205.dkr.ecr.eu-north-1.amazonaws.com/order-service:latest
    container_name: order-service
    restart: unless-stopped
    env_file:
      - ./apps/order-service/.env
    environment:
      REDIS_URL: redis://redis:6379
    expose:
      - "8001"
    depends_on:
      - redis
      - rabbitmq

  payment-service:
    build:
      context: .
      dockerfile: ./apps/payment-service/Dockerfile
    image: 247661383205.dkr.ecr.eu-north-1.amazonaws.com/payment-service:latest
    container_name: payment-service
    restart: unless-stopped
    env_file:
      - ./apps/payment-service/.env
    expose:
      - "8002"
    depends_on:
      - rabbitmq

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    image: 247661383205.dkr.ecr.eu-north-1.amazonaws.com/api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    env_file:
      - ./apps/api-gateway/.env
    environment:
      REDIS_URL: redis://redis:6379
    expose:
      - "8000"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service

  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    image: 247661383205.dkr.ecr.eu-north-1.amazonaws.com/client:latest
    container_name: client
    restart: unless-stopped
    env_file:
      - ./apps/client/.env
    expose:
      - "3002"
    depends_on:
      - api-gateway

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: 247661383205.dkr.ecr.eu-north-1.amazonaws.com/nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - client