
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import { fileURLToPath } from "node:url";
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.resolve(__dirname, ".env") });
dotenv.config({ path: path.resolve(process.cwd(), ".env") });

dotenv.config({ path: path.resolve(process.cwd(), "apps/payment-service/.env") });

dotenv.config({ path: path.resolve(process.cwd(), "packages/paymentdb/.env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
